# Generated by Django 3.2.16 on 2023-04-20 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('organizations', '0004_auto_20230420_1449'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvitedPeople',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=1000, verbose_name='email')),
                ('invited_at', models.DateTimeField(auto_now_add=True, verbose_name='invited at')),
                ('organization', models.ForeignKey(help_text='Organization ID', on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
                ('role', models.ForeignKey(help_text='Role', on_delete=django.db.models.deletion.CASCADE, related_name='role', to='auth.group')),
            ],
            options={
                'db_table': 'invited_people',
            },
        ),
    ]
