# Generated by Django 3.2.16 on 2023-04-23 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('organizations', '0007_auto_20230423_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationmember',
            name='role',
            field=models.ForeignKey(default=4, help_text='Role', on_delete=django.db.models.deletion.CASCADE, related_name='member_role', to='auth.group'),
        ),
    ]
