name: Deploy

on:
  push:
    branches: [ "main" ]

permissions: read-all

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2 

    - name: SSH into EC2 instance + deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          
          if [ ! -f /etc/docker/daemon.json ] || ! grep -q '"buildkit": true' /etc/docker/daemon.json; then
            echo '{"features": {"buildkit": true}}' | sudo tee /etc/docker/daemon.json
            sudo systemctl restart docker
          fi
          
          if [ -d "Nhom01-DeTai01-Label-Studio" ]; then
            cd Nhom01-DeTai01-Label-Studio
            git pull https://github.com/KhaiNguyenDuc/Nhom01-DeTai01-Label-Studio.git && \echo "Pull completed"
            wait
            cd ../
          else
            git clone https://github.com/KhaiNguyenDuc/Nhom01-DeTai01-Label-Studio.git && \echo "Clone completed"
            wait
          fi
          
          sudo docker ps -a --filter ancestor=nhom1/label-studio --format "{{.ID}}" | xargs -r sudo docker stop && \echo "Stop completed"
          sudo docker ps -a --filter ancestor=nhom1/label-studio --format "{{.ID}}" | xargs -r sudo docker rm && \echo "Remove completed"
          
          cd Nhom01-DeTai01-Label-Studio
          chmod -R 755 ./deploy
          sudo apt-get update
          sudo apt-get install -y docker.io
          sudo systemctl start docker
          sudo systemctl enable docker
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          sudo docker-compose down
          sudo docker-compose up -d --build && \echo "Compose completed"
          wait
          sudo docker run -d -p 8080:8080 nhom1/label-studio 
