name: Selenium Test Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.10

    - name: Installed package list
      run: apt list --installed
    - name: Remove Chrome
      run: sudo apt purge google-chrome-stable
    - name: Remove default Chromium
      run: sudo apt purge chromium-browser
    - name: Install a new Chromium
      run: sudo apt install -y chromium-browser

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
        pip install -r deploy/requirements.txt
        pip install -r deploy/requirements-test.txt
        pip install selenium
        pip install webdriver_manager

    - name: Run Selenium tests
      run: |       
        python label_studio/manage.py migrate
        python label_studio/manage.py collectstatic
        python label_studio/manage.py runserver --noreload &
        cd test-label-studio 
        python -m pytest -vv 